# Generated by Django 6.0 on 2025-12-15 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.CharField(help_text='Steam build ID', max_length=50, unique=True)),
                ('game_updated_at', models.DateTimeField(help_text='When the game was last updated (from Steam)')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this data was imported')),
                ('is_active', models.BooleanField(default=True, help_text='Use this version by default')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this version')),
            ],
            options={
                'ordering': ['-game_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text="Faction identifier (e.g., 'human', 'undead')", max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'name'],
                'unique_together': {('version', 'id_key')},
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Hero identifier from game files', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('mesh', models.CharField(blank=True, max_length=100)),
                ('class_type', models.CharField(choices=[('might', 'Might'), ('magic', 'Magic')], max_length=20)),
                ('cost_gold', models.IntegerField()),
                ('start_level', models.IntegerField(default=1)),
                ('start_offence', models.IntegerField(default=0)),
                ('start_defence', models.IntegerField(default=0)),
                ('start_spell_power', models.IntegerField(default=0)),
                ('start_intelligence', models.IntegerField(default=0)),
                ('start_luck', models.IntegerField(default=0)),
                ('start_moral', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(help_text='Complete raw hero data from game files')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='gamedata.faction')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='gamedata.gameversion')),
            ],
            options={
                'verbose_name_plural': 'Heroes',
                'ordering': ['version', 'faction', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Item identifier from game files', max_length=100)),
                ('slot', models.CharField(choices=[('left_hand', 'Left Hand'), ('right_hand', 'Right Hand'), ('armor', 'Armor'), ('head', 'Head'), ('boots', 'Boots'), ('back', 'Back/Cloak'), ('belt', 'Belt'), ('ring', 'Ring'), ('item_slot', 'Item Slot'), ('unic_slot', 'Unique Slot')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('goods_value', models.IntegerField(default=0)),
                ('cost_base', models.IntegerField(default=0)),
                ('cost_per_level', models.IntegerField(default=0)),
                ('max_level', models.IntegerField(default=1)),
                ('item_set', models.CharField(blank=True, help_text='Item set this belongs to', max_length=100)),
                ('raw_data', models.JSONField(help_text='Complete raw item data from game files')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'slot', 'rarity', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Skill identifier from game files', max_length=100)),
                ('skill_type', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Faction', 'Faction')], max_length=20)),
                ('raw_data', models.JSONField(help_text='Complete raw skill data with all levels')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'skill_type', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Spell identifier from game files', max_length=100)),
                ('school', models.CharField(blank=True, choices=[('day', 'Day Magic'), ('night', 'Night Magic'), ('space', 'Space Magic'), ('primal', 'Primal Magic'), ('neutral', 'Neutral Magic')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('raw_data', models.JSONField(help_text='Complete raw spell data from game files')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'school', 'level', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Unit identifier from game files', max_length=100)),
                ('tier', models.IntegerField()),
                ('squad_value', models.IntegerField(help_text='AI value of the unit')),
                ('exp_bonus', models.IntegerField(help_text='Experience gained for killing this unit')),
                ('cost_gold', models.IntegerField(default=0)),
                ('cost_wood', models.IntegerField(default=0)),
                ('cost_ore', models.IntegerField(default=0)),
                ('cost_gemstones', models.IntegerField(default=0)),
                ('cost_crystals', models.IntegerField(default=0)),
                ('cost_mercury', models.IntegerField(default=0)),
                ('hp', models.IntegerField()),
                ('offence', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('damage_min', models.IntegerField()),
                ('damage_max', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('luck', models.IntegerField(default=0)),
                ('moral', models.IntegerField(default=0)),
                ('move_type', models.CharField(default='ground', max_length=20)),
                ('raw_data', models.JSONField(help_text='Complete raw unit data from game files')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='gamedata.faction')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'faction', 'tier', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
    ]
