# Generated by Django 6.0 on 2025-12-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='display_name',
            field=models.CharField(default='', help_text='Localized display name', max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='display_name',
            field=models.CharField(default='', help_text='Localized display name', max_length=200),
        ),
    ]
