# Generated by Django 6.0 on 2025-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_hero_display_name_unit_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together={('version', 'id_key')},
        ),
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly slug from display name', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together={('version', 'id_key'), ('version', 'slug')},
        ),
    ]
