# Generated by Django 6.0 on 2025-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0003_alter_hero_unique_together_hero_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='specialization_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hero',
            name='specialization_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
