# Generated by Django 6.0 on 2025-12-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0004_add_hero_specialization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faction',
            unique_together={('version', 'id_key')},
        ),
        migrations.AddField(
            model_name='faction',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='faction',
            unique_together={('version', 'id_key'), ('version', 'slug')},
        ),
    ]
