# Generated by Django 6.0 on 2025-12-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0005_add_faction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='starting_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
