# Generated by Django 6.0 on 2025-12-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0006_add_hero_sort_and_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_skill',
            field=models.CharField(blank=True, default='', help_text='Faction-specific skill ID', max_length=100),
        ),
    ]
