# Generated by Django 6.0 on 2025-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0007_add_faction_desc_and_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='extracted_values',
            field=models.JSONField(blank=True, default=dict, help_text='Pre-extracted parameter values keyed by level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Faction', 'Faction'), ('Class', 'Class')], max_length=20),
        ),
    ]
