# Generated by Django 6.0 on 2025-12-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0008_add_skill_extracted_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='abilities',
            field=models.JSONField(blank=True, default=list, help_text='List of ability IDs this unit has'),
        ),
        migrations.AddField(
            model_name='unit',
            name='attack_type',
            field=models.CharField(default='melee', help_text='Attack type: melee, ranged, magic', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='damage_modifiers',
            field=models.JSONField(blank=True, default=dict, help_text='Damage modifiers (outDmgMods, inDmgMods, etc.)'),
        ),
        migrations.CreateModel(
            name='CombatModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('skill', 'Hero Skill'), ('ability', 'Unit Ability'), ('spell', 'Spell'), ('item', 'Item'), ('specialization', 'Hero Specialization')], max_length=20)),
                ('source_id', models.CharField(help_text='ID of the source (skill_id, ability_id, etc.)', max_length=100)),
                ('modifier_type', models.CharField(choices=[('outDmgMod', 'Outgoing Damage Modifier'), ('inDmgMod', 'Incoming Damage Modifier'), ('outAllDmgMod', 'Global Outgoing Damage'), ('inAllDmgMod', 'Global Incoming Damage'), ('offence', 'Offence Bonus'), ('defence', 'Defence Bonus'), ('offencePerc', 'Offence Percentage'), ('defencePerc', 'Defence Percentage'), ('damageMin', 'Minimum Damage'), ('damageMax', 'Maximum Damage'), ('crit', 'Critical Chance'), ('critDmg', 'Critical Damage')], max_length=50)),
                ('value', models.FloatField(help_text='Modifier value (percentage as decimal, e.g., 0.10 for 10%)')),
                ('level', models.IntegerField(default=1, help_text='Level at which this modifier applies')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions for modifier (target_tags, damage_type, etc.)')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_modifiers', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'source_type', 'source_id', 'level'],
                'indexes': [models.Index(fields=['version', 'source_type', 'source_id'], name='gamedata_co_version_ed72bd_idx'), models.Index(fields=['version', 'modifier_type'], name='gamedata_co_version_a8598e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Ability identifier from game files', max_length=100)),
                ('ability_type', models.CharField(choices=[('passive', 'Passive'), ('active', 'Active'), ('triggered', 'Triggered')], default='passive', max_length=20)),
                ('raw_data', models.JSONField(help_text='Complete raw ability data from game files')),
                ('extracted_effects', models.JSONField(blank=True, default=dict, help_text='Pre-extracted combat effects (damage mods, stat bonuses, etc.)')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_abilities', to='gamedata.gameversion')),
            ],
            options={
                'verbose_name_plural': 'Unit abilities',
                'ordering': ['version', 'ability_type', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
    ]
