# Generated by Django 6.0 on 2025-12-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0009_combat_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Advanced class identifier', max_length=100)),
                ('class_type', models.CharField(choices=[('might', 'Might'), ('magic', 'Magic')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('activation_conditions', models.JSONField(default=list, help_text='Requirements to unlock')),
                ('required_skill_ids', models.JSONField(default=list, help_text='Pre-extracted skill IDs for quick lookups')),
                ('bonuses', models.JSONField(default=list, help_text='Bonus effects')),
                ('raw_data', models.JSONField(help_text='Complete raw data from game files')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_classes', to='gamedata.faction')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_classes', to='gamedata.gameversion')),
            ],
            options={
                'verbose_name_plural': 'Advanced Classes',
                'ordering': ['version', 'faction', 'class_type', 'id_key'],
                'indexes': [models.Index(fields=['version', 'faction', 'class_type'], name='gamedata_ad_version_544687_idx')],
                'unique_together': {('version', 'id_key')},
            },
        ),
    ]
