# Generated by Django 6.0 on 2025-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0010_advancedclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='start_view_radius',
            field=models.IntegerField(default=6, help_text="Hero's sight radius on the map"),
        ),
    ]
