# Generated by Django 6.0 on 2025-12-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0011_add_hero_view_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_schools', to='gamedata.gameversion')),
            ],
            options={
                'unique_together': {('version', 'id_key')},
            },
        ),
    ]
