# Generated by Django 6.0 on 2025-12-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0012_magicschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='starting_spells',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
