# Generated by Django 6.0 on 2025-12-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0013_add_hero_starting_spells'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Set identifier from game files', max_length=100)),
                ('raw_data', models.JSONField(help_text='Complete raw set data from game files')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sets', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'id_key'],
                'unique_together': {('version', 'id_key')},
            },
        ),
    ]
