# Generated by Django 6.0 on 2025-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0014_add_itemset_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faction',
            options={'ordering': ['version', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='faction',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order from availableFractions in data.json'),
        ),
    ]
