# Generated by Django 6.0 on 2025-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0015_add_faction_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Unit lore/narrative description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='attack_type',
            field=models.CharField(default='melee', help_text='Attack type: melee, ranged, long_reach, magic', max_length=20),
        ),
    ]
