# Generated by Django 6.0 on 2025-12-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0016_add_unit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_type', models.CharField(choices=[('text', 'Localization Text'), ('args', 'Description Arguments')], max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('skills', 'Skills'), ('items', 'Items'), ('spells', 'Spells'), ('abilities', 'Unit Abilities'), ('specs', 'Hero Specializations')], default='general', max_length=20)),
                ('key', models.CharField(help_text='Localization key (e.g., skill_logistics_name)', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('args', models.JSONField(blank=True, default=list)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'category', 'key'],
                'indexes': [models.Index(fields=['version', 'loc_type', 'key'], name='gamedata_lo_version_68852a_idx'), models.Index(fields=['version', 'category'], name='gamedata_lo_version_ee03cb_idx')],
                'unique_together': {('version', 'loc_type', 'category', 'key')},
            },
        ),
    ]
