# Generated by Django 6.0 on 2025-12-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0017_add_localization_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='specialization_data',
            field=models.JSONField(blank=True, default=dict, help_text="Hero's specialization data with bonuses from DB/heroes_specializations/"),
        ),
        migrations.CreateModel(
            name='SubskillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(help_text='Subskill ID (e.g., sub_skill_leadership_2)', max_length=100)),
                ('raw_data', models.JSONField(help_text='Full subskill config with bonuses')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskill_configs', to='gamedata.gameversion')),
            ],
            options={
                'ordering': ['version', 'id_key'],
                'indexes': [models.Index(fields=['version', 'id_key'], name='gamedata_su_version_1e253b_idx')],
                'unique_together': {('version', 'id_key')},
            },
        ),
    ]
