# Generated by Django 5.2.9 on 2025-12-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0018_add_hero_spec_and_subskill_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localization',
            options={'ordering': ['version', 'language', 'category', 'key']},
        ),
        migrations.RemoveIndex(
            model_name='localization',
            name='gamedata_lo_version_68852a_idx',
        ),
        migrations.RemoveIndex(
            model_name='localization',
            name='gamedata_lo_version_ee03cb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='localization',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='localization',
            name='language',
            field=models.CharField(default='en', help_text="Language code (e.g., 'en', 'ru', 'fr', 'zh-hans', 'zh-hant')", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='localization',
            unique_together={('version', 'loc_type', 'category', 'language', 'key')},
        ),
        migrations.AddIndex(
            model_name='localization',
            index=models.Index(fields=['version', 'loc_type', 'language', 'key'], name='gamedata_lo_version_fc59f8_idx'),
        ),
        migrations.AddIndex(
            model_name='localization',
            index=models.Index(fields=['version', 'category', 'language'], name='gamedata_lo_version_49a8fc_idx'),
        ),
    ]
