"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$&wg-_k48iev#^(m3-iymhnflhp12pp7b$4-q@$us+r1_&6y3%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "coykto.pythonanywhere.com",
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    "olden-forge.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'core',
    'gamedata',
    'hero_builder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection and URL prefix handling
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hero_builder.context_processors.available_languages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Two databases:
# - 'default': User data (hero builds, etc.) - NOT tracked in git
# - 'gamedata': Game data (items, spells, units) - tracked in git, read-only in production

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'gamedata': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_gamedata.sqlite3',
    },
}

DATABASE_ROUTERS = ['core.db_router.GameDataRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

# All 14 languages available in Heroes of Might & Magic: Olden Era
LANGUAGES = [
    ('en', 'English'),
    ('cs', 'Čeština'),  # Czech
    ('fr', 'Français'),  # French
    ('de', 'Deutsch'),  # German
    ('hu', 'Magyar'),  # Hungarian
    ('ja', '日本語'),  # Japanese
    ('ko', '한국어'),  # Korean
    ('pl', 'Polski'),  # Polish
    ('ru', 'Русский'),  # Russian
    ('es', 'Español'),  # Spanish
    ('tr', 'Türkçe'),  # Turkish
    ('uk', 'Українська'),  # Ukrainian
    ('zh-hans', '简体中文'),  # Simplified Chinese
    ('zh-hant', '繁體中文'),  # Traditional Chinese
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Optional: Specify where Django should look for translation files
# (Not needed if only using database-backed localizations)
# LOCALE_PATHS = [
#     BASE_DIR / 'locale',
# ]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded and extracted game assets)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Heroes of Might and Magic: Olden Era game data settings
# NOTE: These paths are only needed for import_gamedata command.
# Runtime reads from database. Set to non-existent path for production.
GAME_DATA_PATH = Path(os.environ.get(
    "GAME_DATA_PATH",
    # "/Volumes/BOOTCAMP/Program Files (x86)/Steam/steamapps/common/Heroes of Might & Magic Olden Era Demo/HeroesOE_Data"
    "/Users/eb/Downloads/gamedata/steamapps/common/Heroes of Might & Magic Olden Era Demo/HeroesOE_Data"
))
GAME_DATA_CORE_ZIP = GAME_DATA_PATH / "StreamingAssets" / "Core.zip"
